'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const helpers = require('./helpers.cjs');

const {
  validateSemVer,
  getMajorMinor,
  updatePackageManifests,
  updateReadmeBadges,
  updateCoreSourceModules,
  checkRepositoryVersionSync,
  bumpVersion,
} = require('../scripts/bump-version.cjs');

test('validateSemVer accepts valid SemVer strings and rejects invalid inputs', () => {
  assert.equal(validateSemVer('2.6.0'), '2.6.0');
  assert.equal(validateSemVer('2.7.0'), '2.7.0');
  assert.equal(validateSemVer('3.0.0-rc.1'), '3.0.0-rc.1');

  assert.throws(() => validateSemVer(''), /Invalid semantic version/);
  assert.throws(() => validateSemVer('2.6'), /Invalid semantic version/);
  assert.throws(() => validateSemVer('v2.6.0'), /Invalid semantic version/);
  assert.throws(() => validateSemVer('alpha'), /Invalid semantic version/);
  assert.throws(() => validateSemVer(null), /Invalid semantic version/);
});

test('getMajorMinor extracts major.minor correctly', () => {
  assert.equal(getMajorMinor('2.6.0'), '2.6');
  assert.equal(getMajorMinor('2.7.1'), '2.7');
  assert.equal(getMajorMinor('10.15.2'), '10.15');
});

test('checkRepositoryVersionSync passes on current codebase state', () => {
  const drifts = checkRepositoryVersionSync();
  assert.equal(drifts.length, 0, `Expected 0 drifts, found: ${JSON.stringify(drifts)}`);
});

test('bumpVersion dry-run produces a complete report without touching files', () => {
  const report = bumpVersion('2.7.0', { dryRun: true });
  assert.equal(report.targetVersion, '2.7.0');
  assert.equal(report.majorMinor, '2.7');
  assert.ok(report.manifestsUpdated.length > 0);
  assert.ok(report.readmesUpdated.length > 0);
  assert.ok(report.coreModulesUpdated.length > 0);
});

test('updatePackageManifests and updateReadmeBadges update mock directory atomically', () => {
  const os = require('node:os');
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-mock-'));

  try {
    const mockPkg = { name: '@opengsd/gsd-core', version: '2.5.0' };
    const mockLock = { name: '@opengsd/gsd-core', version: '2.5.0', packages: { '': { version: '2.5.0' } } };
    fs.writeFileSync(path.join(tmp, 'package.json'), JSON.stringify(mockPkg, null, 2));
    fs.writeFileSync(path.join(tmp, 'package-lock.json'), JSON.stringify(mockLock, null, 2));
    fs.writeFileSync(path.join(tmp, 'README.md'), '[![version](https://img.shields.io/badge/version-2.5.0-CB3837)](ROADMAP.md)');

    const changedPkg = updatePackageManifests(tmp, '2.7.0', false);
    assert.deepEqual(changedPkg.sort(), ['package-lock.json', 'package.json']);

    const changedReadme = updateReadmeBadges(tmp, '2.7.0', false);
    assert.deepEqual(changedReadme, ['README.md']);

    const updatedPkg = JSON.parse(fs.readFileSync(path.join(tmp, 'package.json'), 'utf8'));
    assert.equal(updatedPkg.version, '2.7.0');

    const updatedReadme = fs.readFileSync(path.join(tmp, 'README.md'), 'utf8');
    assert.ok(updatedReadme.includes('version-2.7.0-'));
  } finally {
    helpers.cleanup(tmp);
  }
});

test('updateCoreSourceModules updates core TypeScript files in mock directory', () => {
  const os = require('node:os');
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-cts-mock-'));
  const srcDir = path.join(tmp, 'src');
  fs.mkdirSync(srcDir, { recursive: true });

  try {
    fs.writeFileSync(
      path.join(srcDir, 'auto-upgrade-engine.cts'),
      "return { version: '2.5.0', message: 'GSD Core Nexus 2.5 initialized.' };"
    );
    fs.writeFileSync(
      path.join(srcDir, 'living-docs-engine.cts'),
      "> Auto-generated by GSD Core Nexus 2.5 Living Docs."
    );
    fs.writeFileSync(
      path.join(srcDir, 'i18n-descriptions.cts'),
      "// GSD Nexus 2.5 / GSD Core Nexus 2.5"
    );
    fs.writeFileSync(
      path.join(srcDir, 'unified-workflow-hub.cts'),
      "message: 'GSD Core Nexus 2.5 Unified Commands: /gsd:status'"
    );

    const changed = updateCoreSourceModules(tmp, '2.7.0', '2.7', false);
    assert.equal(changed.length, 4);

    const updatedAuto = fs.readFileSync(path.join(srcDir, 'auto-upgrade-engine.cts'), 'utf8');
    assert.ok(updatedAuto.includes("version: '2.7.0'"));
    assert.ok(updatedAuto.includes('GSD Core Nexus 2.7'));

    const updatedLiving = fs.readFileSync(path.join(srcDir, 'living-docs-engine.cts'), 'utf8');
    assert.ok(updatedLiving.includes('GSD Core Nexus 2.7 Living Docs'));
  } finally {
    helpers.cleanup(tmp);
  }
});
